version: "3.9"

services:
  appstore:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./appstore:/appstore
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"