# Generated by Django 4.2.19 on 2025-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
