# Generated by Django 4.2.19 on 2025-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_verified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
