name: Checks

on: [ push ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bengotch/samplepython:latest


      - name: List directory structure
        run: |
          pwd
          ls -l
          ls -l appstore/

      - name: Test
        run: docker-compose run --rm appstore sh -c "python manage.py test"

      - name: Linting
        run: docker-compose run --rm appstore sh -c "flake8"
