---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List directory structure
        run: |
          pwd
          ls -l
          ls -l appstore/
      - name: Test
        run: docker-compose run --rm appstore sh -c "python manage.py test"
      - name: Linting
        run: docker-compose run --rm appstore sh -c "flake8"